### ISSUE TITLE
Mac OS requirement

### ISSUE THREAD

**Issue by zhenyu-zhou** [aixcoder-plugin/doc#1]
As for the [troubleshooting page](https://github.com/aixcoder-plugin/doc/wiki/Troubleshooting#reason-1-your-language-ide-or-operating-system-etc-is-not-supported), do you have a minimum requirement for Mac OS? It looks weird to me that the general "Mac OS X" is listed with specific versions of Windows and Linux.

**Comment by HoratioJSY** [comment]
Mac OS minimum requirement has been fixed as 10.12.
